name: AutoLab Submit

on: [push]

permissions:
  contents: read

jobs:
  submit:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'submit ') 
    steps:
    - uses: actions/checkout@v3
    - uses: JustinKozlowski/AutoLabAutoSubmit@v3
      env:
        UBIT_USERNAME: ${{ secrets.UBITUsername }}
        UBIT_PASSWORD: ${{ secrets.UBITPassword }}
        COMMIT: ${{ github.event.head_commit.message }}
