name: Simple Package Deploy
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install Dependencies
      run: pip install twine pylint pytest coverage ./simple_package
      shell: bash
    - name: Lint
      run: python3 -m pylint simple_package/src/commitparser/parse_commit.py
      shell: bash
    - name: Test
      run: python -m coverage run -m pytest ./simple_package/tests/test_commit_message.py
      shell: bash
    - name: Coverage
      run: python -m coverage report -m --fail-under=80
      shell: bash
    - name: Build
      run: |
        cd simple_package
        python simple_package/setup.py sdist
        twine upload dist/* --username __token__
      shell: bash
    # - name: Push
    #   run: twine upload dist/* --username __token__
    #   shell: bash
        