name: Simple Package Deploy
runs:
  using: "composite"
  steps:
    - name: Pylint 
      run: 
      cd simple_package
      python3 -m venv testenv
      source ./testenv/bin/activate
      pip install pylint
      pylint src/commitparser/parse_commit.py
      shell: bash
    - name: Coverage 
      run: 
      cd simple_package
    # Create and Setup Python environment
      python3 -m venv testenv
      source ./testenv/bin/activate
      pip install pytest
      pip install coverage
      pip install -e .
      cd tests
      coverage run --include=../src/simplepythonpackage/add_one.py -m pytest test_add_one.py
      coverage report -m --fail-under=100
      shell: bash
        