name: Simple Package Deploy
runs:
  using: "composite"
  steps: 
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: cd simple_package; \
           python -m pip install pylint pytest coverage .; \
           python -m pylint src/commitparser/parse_commit.py
      shell: bash

    # - run: cd simple_package; \
    #        source ./testenv/bin/activate ;\
    #        pip install pytest; \
    #        pip install coverage; \
    #        pip install -e .; \
    #        cd tests; \
    #        coverage run --include=../src/commitparser/parse_commit.py -m pytest test_add_one.py; \
    #        coverage report -m --fail-under=100
    #   shell: bash

    # - run: 
    #   cd simple_package
    #   python3 -m venv deployenv
    #   source ./deployenv/bin/activate
    #   pip install twine
    #   python setup.py sdist
    #   twine upload dist/* --username __token__
    #   shell: bash
        