name: Simple Linting
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install Dependencies
      run: pip install pylint ./simple_package
      shell: bash
    - name: Lint
      run: python3 -m pylint commitparser
      shell: bash
