name: Simple Unit Test
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install Dependencies
      run: pip install pytest ./simple_package
      shell: bash
    - name: Test
      run: python -m pytest ./simple_package/tests/test_commit_message.py
      shell: bash
        