name: Python application

on: [push]

permissions:
  contents: write

jobs:
  # hello:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - run: ls

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./actions_examples/pytest
  
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./actions_examples/pylint

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./actions_examples/coverage

  push:
    runs-on: ubuntu-latest
    needs: [lint, coverage]
    steps:
    - uses: actions/checkout@v3
    - uses: ./action_examples/twine
      env:
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
  
  # Uncomment below for autolab submission
  # build:
  #   needs: [push] 
  #   runs-on: ubuntu-latest
  #   if: startsWith(github.event.head_commit.message, 'submit ') 
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: ./
  #     env:
  #       UBIT_USERNAME: ${{ secrets.UBITUsername }}
  #       UBIT_PASSWORD: ${{ secrets.UBITPassword }}

        