name: Python application

on: [push]

permissions:
  contents: write

jobs:
  # hello:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: ./hello_world

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: ./unit_test

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: ./simple_package
  
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: ./simple_package
      env:
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
  
  # Uncomment below for autolab submission
  # build:
  #   needs: [lint, coverage] 
  #   runs-on: ubuntu-latest
  #   if: startsWith(github.event.head_commit.message, 'submit ') 
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: ./
  #     env:
  #       UBIT_USERNAME: ${{ secrets.UBITUsername }}
  #       UBIT_PASSWORD: ${{ secrets.UBITPassword }}

        