name: UB AutoLab Sign Up

on:
  issue_comment:
    types:
      - created

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          ls
          python signup.py
        env:
          NUMBER: ${{ github.event.issue.number }}
          BODY: ${{ github.event.comment.body }}